<a href="https://colab.research.google.com/github/Jdreioe/Numpy_JM/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

testing

# Jonas

# Intro til NumPy

## Oprettelse af array

her oprettes et array

In [ ]:
import numpy as np
data = np.array([5, 7, 10])
data.max()
print(data)

[ 5  7 10]


her er eksempler på simple arrays med ettere og nuller

In [ ]:
ones = np.ones(6)
print(ones)
zeroes = np.zeros(6)
print(zeroes)
random=np.random.random(6)
print(random)

[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]
[0.72068732 0.53846389 0.07009206 0.57685675 0.83950517 0.90994675]


## Array Arithmetic

In [ ]:
print(data+data2)
print(data+data3)

[2. 3. 4.]
[1. 2. 3.]


# Mikkel




In [ ]:
import numpy as np
import math as mth

testdata=np.array([1,2,3,4])
testdata2=np.array([3,4,5,6])




print(testdata[0:2]+testdata2[2:4])
print(testdata[0:2],testdata2[2:4])

[6 8]
[1 2] [5 6]


test34